sudo: required
services:
  - docker

before_install:
  - docker build -t rikertothebridge/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rikertothebridge/react-test npm test

after_success:
  - docker build -t rikertothebridge/multi-client ./client
  - docker build -t rikertothebridge/multi-nginx ./nginx
  - docker build -t rikertothebridge/multi-server ./server
  - docker build -t rikertothebridge/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rikertothebridge/multi-client
  - docker push rikertothebridge/multi-nginx 
  - docker push rikertothebridge/multi-server
  - docker push rikertothebridge/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-429249553478'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
